package com.helios.auctix.domain.user;

public enum AdminActionsEnum {
    USER_BAN,
    USER_UNBAN,
    USER_PROFILE_PHOTO_REMOVE,
    USER_VIEW,
    VERIFICATION_DOCS_APPROVE,
    VERIFICATION_DOCS_VIEW,
    VERIFICATION_DOCS_REJECT,
    VERIFICATION_DOCS_UPDATE;
}
