package com.helios.auctix.domain.user;

public enum UserRequiredActionEnum {
    COMPLETE_PROFILE,
    SELLER_VERIFICATION_DOCUMENT_SUBMISSION,
    ACCOUNT_BANNED_ANNOUNCEMENT,
    SELLER_VERIFIED_ANNOUNCEMENT,
    FIRST_LOGIN_CHANGE_PASSWORD,
    SELLER_VERIFICATION_REJECT_ANNOUNCEMENT,
    PROFILE_PHOTO_REMOVED_ANNOUNCEMENT;
}
